mitxgraders/helpers/calc.py, tests/test_formulagrader.py
An empty string now grades as wrong. This addresses issue #9. Tests fixed too!
=> Fixing bug when empty string submitted to FormulaGrader

mitxgraders/plugins/integralgrader.py, tests/plugins/test_integralgrader.py
This PR improves IntegralGrader's handling of complex numbers. The integrator we use (scipy.integrate.quad) cannot handle complex limits. So:
- Raise a ConfigError if author-specified upper/lower limits evaluate to complex
- Raise an IntegrationError if learner-specified upper/lower limits evaluate to complex
The `scipy.integrate.quad` integrator also cannot handle complex integrands by itself. But we can pass real and imaginary parts to the integrator separately. So this PR adds a configuration option `complex_integrand` (default is False) such that:
- if `complex_integrand:False` and integrand evaluates to complex, raise IntegrationError
- if `complex_integrand:True`, evaluate real/imaginary parts separately and compare author/learner values.
Debug messages and tests also updated.
=> improve IntegralGrader's handling of complex numbers

.gitignore, .travis.yml, pytest.ini, requirements.txt, tests/plugins/test_integralgrader.py
Today I did a fresh install and created a new virtual environment, which revealed a few issues. This PR:
1. Fixes some broken tests in test_integralgrader.py. These tests initially used an unexpected keyword argument in pytest's `raises()` function and so weren't really performing their duty. After `pytest 3.5.1`, unexpected keyword arguments raise errors.
(*I'm not too familiar with our Travis setup. Does it have a hard-coded pytest version? Or does it use something prior to 3.5.1 by default?*)
1. Includes pylint in requirements.txt. 
We have a `.pylintrc` file commited, so I think it makes sense to include pylint in the requirements. Plus, on the few occasions I've decided to do a fresh clone, I've consistently forgotten to install pytest on my venv.
1. Edit: Oh, and pytest changed its …
=> Installation updates

mitxgraders/baseclasses.py
This just tells coverage that there is a line that cannot be tested. While the framework supports adding an overall message to a multi-input problem, nothing can currently generate such a message.
=> Adding no cover option to line that cannot be triggered

docs/README.md, docs/formula_grader.md, mitxgraders/baseclasses.py, mitxgraders/formulagrader.py, mitxgraders/helpers/validatorfuncs.py, mitxgraders/plugins/integralgrader.py, tests/test_formulagrader.py
This addresses #51:
- In FormulaGrader: if variables, numbered_vars, user_constants overlap, raise an error.
- In IntegralGrader: if variables and user_constants overlap, raise an error.
For both FormulaGrader and IntegralGrader, if any user-defined variable/function overrides a default, raise an error that can be suppressed with `suppress_warnings=True`.
=> validate user-defined variables don't conflict, warn if override

mitxgraders/helpers/calc.py, tests/helpers/test_calc.py
This deals with the pyparsing side of allowing vectors to be input into the parser. I haven't made any changes to ensure that they can be correctly manipulated, nor have I put in any error handling to ensure that students get meaningful error messages. I did include a flag to allow/disallow vectors.
=> Allow vectors/matrices in parser

mitxgraders/helpers/calc.py, mitxgraders/helpers/mathfunc.py, tests/helpers/test_calc.py
This does a bunch of tidying in calc.py.
* `evaluator` now has default arguments for variables, functions and suffixes.
* Made all negative signs limited to just one, and made a bunch of tests to ensure compliance.
* Moved one-line pyparsing actions to lambda functions.
* Cleaned up `dump_parse_result`
* Gave names to all symbols in the parser tree, so that you don't see any more `ITEM` tags in the debug dump. Eg., `1+2^-2*sin(x)` now parses to the following debug tree:
```XML
<sum>
<number>
<num>1</num>
</number>
<op>+</op>
<product>
<power>
<number>
<num>2</num>
</number>
<op>-</op>
<number>
<num>2</num>
</number>
</power>
<op>*</op>
<function>
<funcname>sin</funcname>
<arguments>
<variable>
<varname>x</varname>
</variable>
</arguments>
</function>
</product>
</sum>
```
I was trying to …
=> Tidying up calc.py

mitxgraders/baseclasses.py, mitxgraders/formulagrader.py, mitxgraders/helpers/calc.py, mitxgraders/helpers/specify_domain.py, mitxgraders/listgrader.py, mitxgraders/plugins/integralgrader.py, mitxgraders/stringgrader.py, tests/helpers/calc/test_calc.py, tests/test_formulagrader.py, tests/test_listgrader.py
This PR addresses #46 by passing a `siblings` keyword argument to the `check` function of subgraders in a `ListGrader`. This parameter is only available when `ordered=true`.
Currently only FormulaGrader makes any use of `siblings` in its check function. Example:
```python
grader=ListGrader(
answers=['sibling_3 + 1', 'sibling_1^2', 'x'],
subgraders=FormulaGrader(variables=['x']),
ordered=True
)
grader(None, ['x + 1', 'x^2 + 2*x + 1', 'x'])
```
Some notes:
- This is a refactoring of #65, see discussion there.
- No author-facing documentation or course examples, though I've added that to the list of required documentation in #78 
- I've changed the sibling variable names from `input_k` to `sibling_k` to stress that the relationship is relative; particularly relevant when used with grouping / …
=> Pass siblings

mitxgraders/baseclasses.py, mitxgraders/formulagrader/formulagrader.py, mitxgraders/formulagrader/matrixgrader.py, mitxgraders/helpers/calc/formatters.py, mitxgraders/helpers/calc/mathfuncs.py, mitxgraders/helpers/calc/specify_domain.py, tests/formulagrader/test_formulagrader.py, tests/formulagrader/test_matrixformulagrader.py
Provides configuration keys to customize what should happen when a student submits an answer to MatrixGrader that has the wrong shape.
=> Grading incompatible types

MJxPrep.js, mitxgraders/helpers/calc/mathfuncs.py, tests/helpers/calc/test_mathfuncs.py
Quick fix to rename `tr` to `trace`, so as not to confuse with `transpose`. Also added `trace` to javascript file. Documentation not updated, as this is part of a separate PR.
=> Renaming tr to trace

MJxPrep.js
This adds some brackets (important for bras and kets!) as well as hbar to the definition list. None of these are going to interfere with anybody, but this definitely makes my life a little easier... I also added some comments.
=> Adding some extras

mitxgraders/helpers/calc/calc.py, tests/helpers/calc/test_calc_arrays.py
Resolves #108 
Error message is potentially confusing in large expressions. Would be great if `parse_results` included the original string so we could show students what string caused the error. One day, maybe... !
=> disallow multiplication of 3+ vectors w/o parens

docs/changelog.md, docs/grading_math/comparer_functions.md, docs/grading_math/formula_grader.md, docs/item_grader.md, requirements.txt
And some more doc fixes (mostly trouble with nested lists). I had trouble running `mkdocs gh-deploy`, because the `cinder` theme for `mkdocs` isn't compatible with the latest version of `mkdocs`. We should probably look into a new theme at some point. I had to restrict `mkdocs` to an earlier version.
=> Updating docs

mitxgraders/formulagrader/formulagrader.py, mitxgraders/helpers/calc/__init__.py, mitxgraders/helpers/calc/exceptions.py, mitxgraders/helpers/calc/expressions.py, mitxgraders/helpers/calc/robust_pow.py, mitxgraders/plugins/integralgrader.py, requirements.txt, tests/formulagrader/test_formulagrader.py, tests/helpers/calc/test_expressions.py, tests/helpers/calc/test_expressions_arrays.py
Rewrote much of `calc.py` and changed name to `expressions.py`
Noteable changes:
1. I tried to separate parsing and evaluation as much as possible. Usage now looks like:
```python
parser = MathParser()
expr_1 = parser.parse('x + y')
expr_2 = parser.parse('x*y')
variables_A = { 'x': 5, 'y': 7 }
variables_B = {'x': -3, 'y': 4}
expr_1.eval(variables_A, {}, {}, {})
expr_1.eval(variables_B, {}, {}, {}) # evaluate the same expression with different variables, do not re-parse
expr_2.eval(variables_A, {}, {}, {})
expr_2.eval(variables_B, {}, {}, {}) # evaluate the same expression with different variables, do not re-parse
```
2. I changed the grammar so that the **parser** accepts all alphabetic suffixes and '%'. Advantages:
- Allows us to give better error messages for things like `'x + 5y'`. We …
=> rewrite expression parser/evaluator

MJxPrep.js
Just making sure that our new function renders properly :-) I chose to go with `arctan(x, y)` as the render.
=> Adding JS definition for arctan2

mitxgraders/baseclasses.py, tests/test_base.py
This addresses #150 for ItemGraders only. Implementing this for ItemGrader only was very easy because ItemGraders have a strictly specified answers schema.
I suspect we could do something that works in general, but I would need to think a bit more about it.
I wrote this fairly quickly in case you wanted it for today's workshop. I think it should be safe to merge, but feel free to reject if you want a more general solution =).
=> Infer expect

mitxgraders/helpers/calc/expressions.py, tests/formulagrader/test_formulagrader.py, tests/helpers/calc/test_expressions.py
There's a bug in the parser due to the fact that parsing isn't actually stripping out whitespaces. Here's a simple example that trips things up:
```python
from mitxgraders import *
grader = FormulaGrader(variables=['x_{ab}'])
pp(grader('x_{a b}', 'x_{a b}'))
```
(Note that variables cannot have a space in the name.)
This PR fixes the issue.
=> Fixing whitespace parsing

MJxPrep.js
To make it easier to keep track of custom replacements, I've moved the custom replacements into a dedicated function at the very bottom of the script, rather than included in the middle of a complicated function. This is almost a purely cosmetic change.
=> Adding minor cleaning to JS file

MJxPrep.js, mitxgraders-js/MJxPrep.test.js
=> Asciimath nowrap overscripts

mitxgraders/helpers/calc/expressions.py
There are some equality checks in `expressions.py` against strings. These equality checks give rise to warnings when the object being checked against is an array. We need to check if they're strings before doing such a comparison. Note that I'm not sure I caught all of them here.
Here is a minimal working example to see the problem (before this PR):
```python
from mitxgraders import *
grader = MatrixGrader(
variables=['A'],
sample_from={'A': RealMatrices()}
)
print(grader('(A-2*A)^2', '(A-2*A)^2'))
```
I'm also not sure how to test this...
=> Clarifying equality checks when objects may be arrays

docs/grading_math/sampling.md, mitxgraders/sampling.py
This creates a sampler to sample matrices that are scalar multiples of the identity matrix. It determines that scalar by accepting another sampler. To do this, I added an extra abstract subclass of `VariableSamplingSet` called `ScalarSamplingSet`. I also created a new abstract class `AbstractSquareMatrices` that can be used to build up various special types of matrices. Documentation is included.
=> Adding IdentityMatrixMultiples sampler

course/course/course.xml, course/problem/matrix8.xml, docs/grading_math/matrix_grader/matrix_grader.md, mitxgraders/formulagrader/matrixgrader.py, mitxgraders/helpers/calc/exceptions.py, mitxgraders/helpers/calc/expressions.py, mitxgraders/helpers/calc/specify_domain.py, mitxgraders/helpers/validatorfuncs.py, tests/formulagrader/test_matrixgrader.py, tests/helpers/calc/test_specify_domain.py
This PR introduces a flag to `MatrixGrader` that completely suppresses all matrix error messages. This is useful when variables are secretly being used as matrices due to their noncommutativity, but matrix error messages would be confusing to students. Includes code, tests, documentation and course example.
=> Introducing flag to suppress matrix error messages

mitxgraders/listgrader.py, tests/test_listgrader.py
Fixes a bug where ListGraders was having trouble assigning partial credit to problems where `answers` was specified as a tuple of answers.
**Note:** The bugfix is really just transposing one matrix to fix a shape comparison. I believe the bug has gone undetected until now because our test case used 2 inputs and had 2 author-supplied answer, and transpose of a 2x2 is 2x2.
@jolyonb I believe this fixes the issue your 8.06 student encountered. I really would like to go over the code more carefully, add comments, etc, but you have an exam running and I'm about to get off my bus!  I did add a more descriptive docstring.
=> fix bug partial credit for multi-answer ListGrader

docs/grading_lists/single_list_grader.md, mitxgraders/__init__.py, mitxgraders/listgrader.py, tests/test_singlelistgrader.py
Adds an option to SingleListGrader to detect and present an error if there are empty entries in a list, turned on by default.
Includes tests and documentation (I started converting the examples to doctests).
Resolves #167.
=> Updating SingleListGrader to detect missing entries

mitxgraders/comparers/__init__.py, mitxgraders/comparers/baseclasses.py, mitxgraders/comparers/comparers.py, tests/formulagrader/test_formulagrader.py
Creates a comparer that applies a python function to the expected result and student input before performing the comparison. I thought about doing this based on string references to functions the grader already knows about, before realizing that comparers don't have access to the function listing etc.
In order to implement this, I created a new base class `Comparer`, of which `CorrelatedComparer` is a subclass. I also made an `EqualityComparer` class from which `equality_comparer` derives.
Question: Do you think that I should just merge `ApplyFunctionComparer` into `EqualityComparer`? They're almost copies of each other.
Resolves #192.
=> Adding the ApplyFunctionComparer comparer

mitxgraders/formulagrader/formulagrader.py, mitxgraders/helpers/calc/expressions.py, tests/formulagrader/test_formulagrader.py, tests/helpers/calc/test_expressions.py, tests/test_listgrader.py
This introduces instructor variables, which can be used to remove a variable for use in student evaluations. This is useful when a variable is needed for DependentSampler, and can also be used to remove predefined constants.
This PR also prettifies some FormulaGrader error messages by adding quotation marks.
Resolves #160
=> Introducting instructor variables

codecov.yml, mitxgraders/__init__.py, mitxgraders/matrixsampling.py, mitxgraders/sampling.py, tests/test_matrixsampling.py
This PR brings the long-awaited matrix sampling structure together. It largely follows the structure laid out in #188; biggest difference is that I went for a `dimension` property for square matrices instead of `shape`. We can now sample matrices of all types!
Resolves #188
Resolves #148
Resolves #83 (about time!)
=> Setting up Matrix Sampling

MJxPrep.js
This one is pretty simple. I found that some javascript replacements I was doing were interfering with wrapping, so I needed a separate function to run after wrapping occurred.
=> Adding cosmetic replacement function to javascript

requirements.txt, requirements3.txt
I tried setting up a fresh install of this repo in python 2 and 3. The python 2 version is failing because pylint doesn't install properly. We're not actually using it, so I'm removing it from requirements.txt.
=> Removing pylint from requirements.txt

mitxgraders/matrixsampling.py
This updates the matrixsampling tests that use upgraded numpy/scipy features to dynamically skip the tests in python 2.
=> Updating matrix sampling tests to skip python 3 tests in python 2

README.md
Just fixing the `README.md` file so that the coverage badge links to codecov.io.
=> Linking coverage badge to coverage report

mitxgraders/baseclasses.py, mitxgraders/stringgrader.py, tests/test_base.py
This PR introduces the ability to have decreasing credit on increasing attempt number. See [this PR](https://github.com/edx/edx-platform/pull/18149) at edX which introduces the required feature and gives an example of how to use it.
I decided against including a feature to have a plugin set course-wide defaults for this, as that's a separate feature that could be used to set defaults for any option in any grader. I've made a new issue for such a feature.
Resolves #137
=> Setting up attempt-based grading

mitxgraders/baseclasses.py, mitxgraders/comparers/baseclasses.py, mitxgraders/matrixsampling.py, mitxgraders/plugins/defaults_sample.py, mitxgraders/plugins/template.py, mitxgraders/sampling.py, tests/test_base.py
Pretty much what it says in the title.
This was a tricky little thing to get right, and involved my first ever use of my own metaclass. The basic idea is to have a `default_values` property associated with each class (not class instance, but _class_; hence the need for a metaclass). Then, right before schema validation, look up the class `default_values` property, _and all of the superclasses_, to construct the complete configuration. I think the end result is really neat though, and provides a really easy way to set global defaults.
Resolves #249.
=> Adding plug-in to do global default overrides

mitxgraders/formulagrader/formulagrader.py
This fixes a small issue with the implementation of instructor variables: they need to be added back in to the debug output. I haven't made a test to fix this, because it's one of those functiongrader debug log things (I was going to co-opt the corresponding sibling variable test, but found that there wasn't one for that either!).
=> Adding instructor variables back in to debug output

mitxgraders/formulagrader/formulagrader.py
Simple fix for a typo I missed previously.
I think I've been through the vast majority of the lines of code in both `ListGrader`, `SingleListGrader` and `FormulaGrader` of late. I'm really impressed with the sophistication of what we've built!
=> Fixing typo in FormulaGrader

mitxgraders/listgrader.py, tests/test_listgrader.py
Implements a partial credit switch for `ListGrader` (which previously had partial credit always on). Works correctly in nested lists, so that partial credit can be turned off for a sublist, but left on for the outermost list.
Resolves #245
=> Option to turn off partial credit in ListGrader

mitxgraders/baseclasses.py, mitxgraders/listgrader.py, tests/test_base.py, tests/test_singlelistgrader.py
This PR generalizes the implementation of reading the `expect` keyword to infer answers. In particular, it does the following:
* Makes it explicit that once an answer is inferred, that answer is stored in the configuration
* Ensures that when answers are being inferred, newly-provided `expect` parameters override the old ones
* Adds the inferred answers to the debug log
* Generalizes the debug log implementation slightly to provide access to it before the `AbstractGrader.__call__` function is called, while ensuring that the log is cleared between calls to a grader
* Implements answer inference as a shadowable function
* Implements answer inference for `SingleListGrader`
* Implements proper delimiter checking across nested `SingleListGrader`s
=> Infer answers from expect values for SingleListGrader

mitxgraders/matrixsampling.py, tests/test_matrixsampling.py
I've noticed that the matrix sampling tests often error on my machine, coming in just under the given tolerances (particularly on unit determinant and unit norm tests). This just relaxes those tolerances slightly so that tests don't fail when things are really doing ok.
=> Relaxing tolerances on matrix tests

mitxgraders/baseclasses.py, mitxgraders/formulagrader/formulagrader.py, mitxgraders/listgrader.py, tests/test_singlelistgrader.py
This PR updates the answer validation for SingleListGrader. It actually leverages `ItemGrader` in a neat way that makes everything nicer, in my opinion. Addresses #247 for SingleListGrader (but not ListGrader, which is a whole 'nother beast!).
The code:
```python
grader = SingleListGrader(
answers=['a', 'b'],
subgrader=StringGrader()
)
pprint.pprint(grader.config['answers'])
```
currently produces:
```python
([({u'expect': u'a', u'grade_decimal': 1, u'msg': u'', u'ok': True},),
({u'expect': u'b', u'grade_decimal': 1, u'msg': u'', u'ok': True},)],)
```
whereas in the overhaul, it produces:
```python
({u'expect': [({u'expect': u'a',
u'grade_decimal': 1,
u'msg': u'',
u'ok': True},),
({u'expect': u'b',
u'grade_decimal': 1,
u'msg': u'',
u'ok': True},)],
u'grade_decimal': 1,
u'msg': u'',
u'ok': …
```
=> Overhauling SingleListGrader answer structure, validation and grading

docs/edx.md, docs/faq.md, docs/graders.md, docs/index.md, docs/item_grader.md, docs/plugins.md, docs/string_grader.md, mitxgraders/plugins/defaults_sample.py, mkdocs.yml
This updates all documentation that is not in the `grading_lists` or `grading_math` subdirectories.
=> Non-mathy and non-listy documentation

mitxgraders/helpers/calc/mathfuncs.py, mitxgraders/helpers/calc/specify_domain.py, tests/formulagrader/test_formulagrader.py, tests/helpers/calc/test_expressions.py, tests/helpers/calc/test_specify_domain.py
Resolves #166 by allowing SpecifyDomain to have a `min_length` argument.
Also incorporates math functions `min` and `max`.
=> Expanding SpecifyDomain to allow for functions with any number of arguments of a given shape

mitxgraders/comparers/linear_comparer.py, mitxgraders/formulagrader/formulagrader.py, mitxgraders/formulagrader/matrixgrader.py, tests/comparers/test_linear_comparer.py
Caught a little bug in LinearComparer when writing documentation. We need to have at least 3 samples for the comparison to be meaningful!
In particular, NumericalGrader/MatrixGrader/FormulaGrader all shared the same default grader, if it was set on FormulaGrader. This decouples everything.
=> Fixing bug with LinearComparer with less than 3 samples

requirements.txt, requirements3.txt
I ran into this problem after reinstalling my virtual env: the mkdocs-cinder theme had been updated. I've forced mkdocs-cinder to be an old version (they're up to 0.17 now), but we should probably update mkdocs and mkdocs-cinder to latest versions at some point.
=> Restricting mkdocs-cinder version

mitxgraders/comparers/comparers.py
The schema `Any(All(Number, Range(0, 1)), 'proportional')` allows `True` as an input, which evaluates to 1. This caught me out when making an example - it should complain if you give it `True`, when you probably mean `'proportional'` instead.
=> Fixing issue with MatrixGrader voluptuous schema

mitxgraders/baseclasses.py, tests/formulagrader/test_formulagrader.py, tests/formulagrader/test_integralgrader.py, tests/helpers/calc/test_specify_domain.py
This coerces all arguments provided in `ObjectWithSchema` configs to unicode as necessary.
I don't know a good way to test that this works explicitly. Suggestions welcome.
Resolves #238
=> Coerce all inputs to unicode

mitxgraders/sampling.py, tests/test_sampling.py
This adds an extra check to DependentSampler that we somehow missed previously. Also updates tests; should get us back to 100% coverage.
=> Adding extra error check to DependentSampler, fixing test coverage

course/problem/string6.xml, docs/graders.md, mitxgraders/__init__.py, mitxgraders/attemptcredit.py, mitxgraders/baseclasses.py, tests/test_base.py
This overhauls attempt-based partial credit. I think it's an improvement over the API I previously implemented, as it allows for maximum flexibility, while useful defaults are provided.
=> Generalizing attempt-based partial credit

course/problem/singlelist3.xml, docs/edx.md, docs/grading_lists/single_list_grader.md, mitxgraders/listgrader.py, tests/test_singlelistgrader.py
This is useful when providing grade_decimal or msg entries in answers, as it means you don't need to construct a list of individual entries, but rather just specify the string that is expected from students.
=> Allow SingleListGrader answers to be specified as a string

docs/grading_math/formula_grader.md, docs/grading_math/matrix_grader/matrix_grader.md, mitxgraders/formulagrader/formulagrader.py, mitxgraders/formulagrader/matrixgrader.py, mitxgraders/helpers/calc/mathfuncs.py, tests/formulagrader/test_formulagrader.py
Introduces a flag to allow infinities to appear in FormulaGrader expressions (but not matrix expressions).
=> Adding allow_inf flag to FormulaGrader

mitxgraders/comparers/linear_comparer.py
LinearComparer was failing for linear comparisons when students provided a constant response.
```
from mitxgraders import *
grader = FormulaGrader(
answers={'comparer': LinearComparer(proportional=None, linear=1), 'comparer_params': ['x']},
variables=['x'],
sample_from={
'x': [0.1, 10]
},
samples=50
)
print(grader(None, 'x'))  # works fine
print(grader(None, '1'))  # error
```
Issue was traced to the way that numpy least squares calculations handle singular inputs.
=> Fixing bug in linear comparer

docs/grading_math/formula_grader.md, mitxgraders/helpers/math_helpers.py, mitxgraders/sampling.py, tests/formulagrader/test_formulagrader.py
This allows an instructor to set a pre-defined constant to `None` to remove it from the list of constants.
=> Implementing functionality to remove default math constants

mitxgraders/helpers/calc/expressions.py, tests/helpers/calc/test_expressions.py
Hi!  Someone reported an issue when pasting some math into an input field on edx.  Some confusion arose around a unicode look-a-like character that looks like a dash, but is, in fact an emdash!  Here they are:
`emdash: –` 
`dash..:      -`
The problem was that the mitx-grading-library parser was expecting an ascii dash but instead got an emdash.  So, the user got a syntax error.  This commit fixes that problem by adding a rule that tokenizes emdashes and immediately converts them to ascii dashes.
=> Input sanitizing, parsing emdash as minus sign, adds some tests for that.

.github/workflows/ci.yaml, docs/changelog.md, docs/item_grader.md, mitxgraders/baseclasses.py, mitxgraders/formulagrader/intervalgrader.py, mitxgraders/listgrader.py, pytest.ini, tests/formulagrader/test_formulagrader.py, tests/formulagrader/test_intervalgrader.py, tests/test_base.py, tests/test_singlelistgrader.py
Addresses #282 by allowing expect values to consist of a tuple of options.
The modifications to `ItemGrader` were pretty straightforward; propagating these changes to `post_schema_ans_val` was a little messy.
This is a work in progress: this needs extensive tests and documentation.
=> Implementing tuple options for expect values

.github/workflows/integration-test.yaml, integration_tests/integration_test.py
This PR adds a workflow that validates functionality based on the named releases.
Based on the [library documentation](https://mitodl.github.io/mitx-grading-library/):
> The mitxgraders Python library provides a number of configurable Python classes that can be used as graders in edX custom response problems.
So, this PR launches a Tutor env with codejail and runs a script containing the Python classes used by this library.
This PR only tests that you can use the principal classes, but it doesn't test the correctness of each class; for that, we have the unit tests.
> [!IMPORTANT]
> Adding this workflow increases the execution time.
> The unit test runs in seconds, and this integration test runs in ~9 minutes.
> [!NOTE]  
> This test shows that the `python_lin.zip` file works as expected …
=> feat: add integration tests
