mitodl/mitx-grading-library

.travis.yml
tests/test_zip.py

Adds Travis continuous integration testing to the repository.
I also had to modify the zip test, as it was failing on Travis.

Adding travis integration

---

.travis.yml
README.md

Trying to set up coveralls on this repo.
Also adding travis badge to the README.

Adding coveralls

---

pytest.ini

Exactly what it says on the tin. Apparently our doctests weren't being included in the test suite...

Adding doctests back into the test suite

---

tests/test_zip.py

use test_zip.py's path to locate python_lib.zip

---

mitxgraders/helpers/calc.py
tests/test_formulagrader.py

Address #20 
This adds a few more Exception classes to `calc.py` for catching division by zero, overflow, and some other function evaluation errors.

Catch & handle zero division, overflow, and function eval errors

---

.coveragerc
mitxgraders/__init__.py
mitxgraders/baseclasses.py
mitxgraders/formulagrader.py
mitxgraders/helpers/calc.py
mitxgraders/helpers/validatorfuncs.py
mitxgraders/listgrader.py
mitxgraders/plugins/integralgrader.py
mitxgraders/sampling.py
tests/plugins/test_integralgrader.py
tests/test_base.py
tests/test_formulagrader.py
tests/test_listgrader.py
tests/test_sampling.py
tests/test_singlelistgrader.py

In the spirit of procrastination, I've added some tests to increase coverage of the library. Lo and behold, as I did so, I found a handful of bugs! I also took the opportunity to do a little linting.
We now have 100% coverage! (minus one line...)

Adding tests to increase coverage

---

README.md

Adding documentation for a funny virtualenv issue.

Adding FAQ section to README.md

---

docs/formula_grader.md
mitxgraders/formulagrader.py
mitxgraders/helpers/calc.py
mitxgraders/plugins/integralgrader.py
mitxgraders/sampling.py
tests/plugins/test_integralgrader.py
tests/test_base.py
tests/test_formulagrader.py

Partially addresses #26. Documentation has been updated appropriately. Also fixes some issues in tests.

Removing case-insensitive input for FormulaGrader, IntegralGrader

---

mitxgraders/helpers/calc.py

This addresses #60 by removing unnecessary groups (`atom` and `parentheses`, whose eval functions just returned the group children) and by conditionally grouping sum/product/parallel/power/negate only if there are children.
This generates much cleaner parse trees. For example, `3^2+(2)` generates
```xml
<sum>
<power>
<number>
<ITEM>3</ITEM>
</number>
<number>
<ITEM>2</ITEM>
</number>
</power>
<ITEM>+</ITEM>
<number>
<ITEM>2</ITEM>
</number>
</sum>
```
whereas the old version would generate:
```xml          
<sum>
<product>
<parallel>
<negation>
<power>
<atom>
<number>
<ITEM>3</ITEM>
</number>
</atom>
<atom>
<number>
<ITEM>2</ITEM>
</number>
</atom>
</power>
</negation>
</parallel>
</product>
<ITEM>+</ITEM>
<product>
<parallel>
<negation>
<power>
<atom>
<parentheses>
<sum>
<product> …
```

simplify the generated parse tree

---

mitxgraders/helpers/validatorfuncs.py

make get_number_of_args positional only

---

mitxgraders/formulagrader.py
mitxgraders/helpers/mitmath/calc.py
mitxgraders/helpers/mitmath/math_array.py
mitxgraders/helpers/mitmath/mathfuncs.py
mitxgraders/plugins/integralgrader.py
tests/helpers/math/test_calc.py
tests/helpers/math/test_calc_arrays.py
tests/test_formulagrader.py

Resolves #67.
Consolidates error handling in calc.py and streamlines handling of infinities and NaNs.

Consolidating error checking for NaN and inf

---

mitxgraders/baseclasses.py
mitxgraders/listgrader.py
tests/test_listgrader.py

Resolves #64.
This one was surprisingly simple.

Extended debug logs to nested graders

---

mitxgraders/helpers/calc/math_array.py
mitxgraders/helpers/calc/specify_domain.py
tests/helpers/math/test_math_array.py

This resolves #89. In multiplication, if output array contains a single item, convert it to a number.

if matharray product is 1 item, return a number

---

mitxgraders/formulagrader/formulagrader.py
tests/formulagrader/test_formulagrader.py
tests/helpers.py

Sibling fix

---

mitxgraders/helpers/calc/calc.py
tests/helpers/calc/test_calc.py

Improve isinf isnan checks

---

.gitignore
mitxgraders-js/package-lock.json
mitxgraders-js/package.json
mitxgraders-js/renderer.js
mitxgraders-js/renderer.test.js

Add jest for testing js files in `mitxgraders-js` directory. Does not transpile any javascript (e.g., no babel).

create js dir with jest for tests

---

MJxPrep.js
mitxgraders-js/MJxPrep.js
mitxgraders-js/MJxPrep.test.js
mitxgraders-js/renderer.js
mitxgraders-js/renderer.test.js

This implements bracket finding in the javascript preprocessor. It also tidies up the javascript file and implements testing nicely.

Implement bracket finding in javascript preprocessor

---

.travis.yml

This gets Travis to check javascript as well as python!

Implementing js testing in travis

---

MJxPrep.js
mitxgraders-js/MJxPrep.test.js

This PR updates the javascript preprocessor substantially.
* `dagger` is defined in AsciiMath
* `fact` and `factorial` are fixed
* `ctrans` and `adj` are implemented
* `replaceFunctionCalls` has some extra logic added to make sure that it only affects the desired functions
* `conj` is implemented as a star when the option is set
* Lots of tests!

Javascript updates

---

MJxPrep.js
mitxgraders-js/MJxPrep.test.js

Display cross products and vectors as described in #95

Js updates 2

---

MJxPrep.js
mitxgraders-js/MJxPrep.test.js

process string even if some errors present

---

MJxPrep.js
mitxgraders-js/MJxPrep.test.js

do not convert 0 & 1 component vectors to columns

---

mitxgraders/helpers/calc/calc.py
mitxgraders/helpers/calc/exceptions.py
mitxgraders/helpers/calc/math_array.py
tests/formulagrader/test_formulagrader.py
tests/helpers/calc/test_calc_arrays.py

Resolves #124 
Also implements #123 without errors.

Convert np scalars

---

mitxgraders/helpers/calc/math_array.py
requirements.txt
tests/helpers/calc/test_math_array.py

Addresses #131 
@jolyon Nearly singular things might still behave badly? You probably know better than me...

implement try/catch for singular matrices in __pow__

---

MJxPrep.js
mitxgraders-js/MJxPrep.test.js

Does what it says, and reorganized javascript tests slightly.
I updated the edge course to see it live... perhaps I should have waited. The uploader script is really great.

wrap function calls in unbreakable invisible braces

---

MJxPrep.js

Addresses #163 
This fix seems a bit hacky; I don't entirely understand the underlying issue.

asciimath conj fix

---

mitxgraders-js/package-lock.json
mitxgraders-js/package.json
mitxgraders/comparers/__init__.py
mitxgraders/comparers/comparers.py
mitxgraders/formulagrader/formulagrader.py
mitxgraders/helpers/calc/math_array.py
mitxgraders/helpers/calc/mathfuncs.py

Addresses #174 by implementing `vector_span_comparer` and `vector_phase_comparer`
Notes:
- I decided not to implement `vector_parallel_comparer`; just use `vector_span_comparer` with one vector.
- Comparer functions `comparer_params` currently have no validation. For example, `vector_span_comparer` expects comparer params to be a list of equal-length vectors. If a list of unequal length vectors is provided, a generic "Input cannot be graded" message is shown, although a more informative message is displayed when `debug=True`.

Vector comparers

---

README.md

Fixing README.md link

---

docs/grading_math/formula_grader.md
docs/grading_math/sampling.md

Addresses #171 by adding documentation about possible variable names (not sure why this was previously completely omitted! Either that, or I'm blind...).

Documenting variable names

---

mitxgraders/formulagrader/formulagrader.py
mitxgraders/plugins/integralgrader.py
mitxgraders/sampling.py
tests/test_sampling.py

give dependent sampler access to constants

---

mitxgraders/__init__.py

Import comparers directly from `mitxgraders`

import all comparers

---

mitxgraders/baseclasses.py
mitxgraders/stringgrader.py
tests/test_stringgrader.py

This PR adds a bunch of upgrades to `StringGrader`:
* Adds a minimum character count and a minimum word count when accepting all entries
* Adds new flags to determine how to treat whitespace
* Cleans up and expands the implementation of input cleaning
* Implements regex validation of inputs
While I was at it, I updated some docstrings in `baseclasses.py`.
This PR includes functionality and tests, but not documentation. I'm leaving that for later.
Resolves #190

Adding multiple features to StringGrader

---

docs/grading_math/formula_grader.md
docs/grading_math/sampling.md

Resolves #201. Turns out the feature was documented, just not where I was looking.

Tidying docs slightly

---

.travis.yml
mitxgraders/comparers/linear_comparer.py
mitxgraders/helpers/calc/expressions.py
mitxgraders/helpers/calc/math_array.py
mitxgraders/helpers/calc/robust_pow.py
mitxgraders/helpers/get_number_of_args.py
mitxgraders/helpers/validatorfuncs.py
mitxgraders/plugins/integralgrader.py
mitxgraders/sampling.py
tests/formulagrader/test_formulagrader.py
tests/plugins/test_integralgrader.py

(Hopefully) final code updates for Python 2 / 3 compatibility. All tests are passing in Python 2 and Python 3.
Re coverage: visual inspection shows no line missing in both coverage reports (Py2, Py3)
Going to look into automating the simultaneous testing / combined coverage.

Py23 all passing

---

mitxgraders/helpers/validatorfuncs.py
mitxgraders/sampling.py

Pretty much what it says on the tin. Just needed to allow for a more general voluptuous schema.
Resolves #184

Allowing DiscreteSet to work with MathArrays

---

mitxgraders/comparers/linear_comparer.py
mitxgraders/helpers/calc/expressions.py
mitxgraders/helpers/calc/math_array.py
mitxgraders/helpers/calc/mathfuncs.py
mitxgraders/helpers/get_number_of_args.py
mitxgraders/matrixsampling.py
requirements.txt
requirements3.txt
tests/test_matrixsampling.py

This branch aims to upgrade to pytest 4.6.4, and address various issues that this upgrade raises.
Resolves #237

Upgrading to pytest 4.6.4

---

.travis.yml

Adding python 3.6 to Travis

---

mitxgraders/listgrader.py
tests/test_singlelistgrader.py

This validates that the configuration for `SingleListGrader` does not have any empty answers, if such answers would require the student to enter an answer that would run afoul of the `missing_error` setting.

Ensure answers provided to SingleListGrader are nonempty

---

mitxgraders/baseclasses.py
tests/test_base.py

Reports registered defaults in the debug log output.
Resolves #258.

Adding modified defaults to debug log

---

mitxgraders/comparers/__init__.py
mitxgraders/comparers/comparers.py
mitxgraders/formulagrader/matrixgrader.py
tests/formulagrader/test_formulagrader.py
tests/formulagrader/test_matrixgrader.py

Adds MatrixEntryComparer, a configurable grader that implements partial credit for matrices based on entry.

Matrix partial credit

---

mitxgraders/comparers/comparers.py
tests/formulagrader/test_matrixgrader.py

Just some minor changes to MatrixEntryComparer that got lost in translation somewhere across the mid-west ;-)

Minor comment updates for MatrixEntryComparer

---

mitxgraders/plugins/defaults_sample.py

Adding plugin example for partial credit in MatrixGrader

---

docs/grading_lists/list_grader.md
docs/grading_lists/single_list_grader.md
docs/index.md
docs/item_grader.md
mkdocs.yml

This updates the documentation for ListGrader and SingleListGrader to version 2.0. I also decided that SingleListGrader should come before ListGrader in the documentation, as it's a simple grader.

Updating listgrader and singlelistgrader documentation 

---

docs/changelog.md
docs/grading_math/sampling.md
mitxgraders/helpers/calc/expressions.py
mitxgraders/sampling.py
tests/formulagrader/test_formulagrader.py
tests/test_sampling.py

This does two things:
- Makes DependentSampler parse the formula to compute dependencies
- Gives DependentSampler access to user_functions (this was actually already done, but wasn't documented properly!)
Also provides some minor linting.
Resolves #271

DependentSampler upgrades

---

tests/test_base.py

This PR includes tests for #277

Testing coerce2unicode

---

MJxPrep.js
README.md
docs/changelog.md
mitxgraders/version.py

Addresses #283 
I'm surprised we didn't catch this before 🤷‍♂ 
I tested this on my personal version of demo course, but have not pushed to "public" demo course.
I also bumped version number and changelog. (And I found 3 typos. So I've found 3, and you've found 500 of mine 😄 )

do not wrap lonesome sqrts

---

mitxgraders/formulagrader/__init__.py
mitxgraders/formulagrader/intervalgrader.py
mitxgraders/listgrader.py
tests/formulagrader/test_intervalgrader.py

This implements IntervalGrader. It's based on a SingleListGrader. Students type in `[1, 2)` or similar. By default, comparisons are done with high (absolute) precision NumericalGraders, but FormulaGraders can also be used. I made the decision that the bracket and the bound are treated as one unit for the purpose of partial credit.
Tests included, but no documentation/examples yet. That'll be next.

IntervalGrader

---

mitxgraders/helpers/calc/__init__.py
mitxgraders/helpers/calc/expressions.py
mitxgraders/helpers/math_helpers.py
mitxgraders/sampling.py

Make vars available

---

mitxgraders/formulagrader/__init__.py
mitxgraders/formulagrader/integralgrader.py
tests/formulagrader/test_sumgrader.py

What it says on the tin. Includes tests, but no documentation/examples as of yet.

Implementing sumgrader

---

mitxgraders/helpers/math_helpers.py
tests/formulagrader/test_formulagrader.py
tests/formulagrader/test_integralgrader.py
tests/formulagrader/test_sumgrader.py

Updating math debug messages to remove angle brackets

---

mitxgraders/formulagrader/formulagrader.py
mitxgraders/helpers/math_helpers.py
tests/formulagrader/test_formulagrader.py
tests/helpers/calc/test_expressions.py
tests/test_listgrader.py

The purpose of this PR is to rearrange how siblings are sampled, in order to allow them to appear in a DependentSampler.

Rearranging sibling sampling

---

mitxgraders/formulagrader/integralgrader.py
mitxgraders/helpers/calc/mathfuncs.py
mitxgraders/matrixsampling.py

lazily import scipy to avoid import delay
